### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: org/apache/avro/io/DatumWriter error

### ISSUE THREAD

**Issue by sivapolisetty** [farmdawgnation/registryless-avro-converter#10]
Hi . 

Please help in understand how to run this. I kept kafka-connect-jdbc-5.5.1.jar, postgresql-42.2.10.jar and registryless-avro-converter-1.10.0.jar in plugins folder. I am running **"connect-standalone.sh worker-local.properties  postgres-sink-connector-local.properties"**. 

I am getting following error ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:130)
java.lang.NoClassDefFoundError: org/apache/avro/io/DatumWriter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:719)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:474)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:467)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
	at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:399)
	at org.apache.kafka.connect.runtime.standalone.StandaloneConfig.<init>(StandaloneConfig.java:42)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:81)
Caused by: java.lang.ClassNotFoundException: org.apache.avro.io.DatumWriter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by farmdawgnation** [comment]
Hi there,

This plugin requires the Confluent Avro Converter to also be on the class path. We leverage some shared code. Can you ensure you have a copy of that in your plug-ins folder?

**Comment by realradical** [comment]
i put both registryless converter jar and Avro Converter in plugin folder. getting the same error

**Comment by rgthorn** [comment]
Hi, we got this working by adding the jar file to the CLASSPATH variable.
