### ISSUE TITLE
"Not an avro file" error

### ISSUE THREAD

**Issue by AdamUrbanfox** [farmdawgnation/registryless-avro-converter#16]
I am attempting to use the registryless avro converter to deserialise avro records from Kafka using Kafka connect and pipe them into AWS kinesis using the kinesis stream sink plugin for Kafka connect. I've provided the schema file as below:
`{
    "namespace": "io.divolte.record",
    "type": "record",
    "name": "DefaultEventRecord",
    "fields": [
        { "name": "detectedDuplicate",       "type": "boolean" },
        { "name": "detectedCorruption",      "type": "boolean" },
        { "name": "firstInSession",          "type": "boolean" },
        { "name": "timestamp",               "type": "long" },
        { "name": "clientTimestamp",         "type": "long" },
        { "name": "remoteHost",              "type": "string" },
        { "name": "referer",                 "type": ["null", "string"], "default": null },
        { "name": "location",                "type": ["null", "string"], "default": null },
        { "name": "viewportPixelWidth",      "type": ["null", "int"],    "default": null },
        { "name": "viewportPixelHeight",     "type": ["null", "int"],    "default": null },
        { "name": "screenPixelWidth",        "type": ["null", "int"],    "default": null },
        { "name": "screenPixelHeight",       "type": ["null", "int"],    "default": null },
        { "name": "partyId",                 "type": ["null", "string"], "default": null },
        { "name": "sessionId",               "type": ["null", "string"], "default": null },
        { "name": "pageViewId",              "type": ["null", "string"], "default": null },
        { "name": "eventType",               "type": "string",           "default": "unknown" },
        { "name": "userAgentString",         "type": ["null", "string"], "default": null },
        { "name": "userAgentName",           "type": ["null", "string"], "default": null },
        { "name": "userAgentFamily",         "type": ["null", "string"], "default": null },
        { "name": "userAgentVendor",         "type": ["null", "string"], "default": null },
        { "name": "userAgentType",           "type": ["null", "string"], "default": null },
        { "name": "userAgentVersion",        "type": ["null", "string"], "default": null },
        { "name": "userAgentDeviceCategory", "type": ["null", "string"], "default": null },
        { "name": "userAgentOsFamily",       "type": ["null", "string"], "default": null },
        { "name": "userAgentOsVersion",      "type": ["null", "string"], "default": null },
        { "name": "userAgentOsVendor",       "type": ["null", "string"], "default": null }
    ]
}
`
When my connector tries to deserialise the records produced to Kafka by Divolte collector, it throws the error
`Caused by: org.apache.avro.InvalidAvroMagicException: Not an Avro data file.
kafka-connect  | 	at org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:111)
kafka-connect  | 	at org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:139)
kafka-connect  | 	at org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:131)
kafka-connect  | 	at me.frmr.kafka.connect.RegistrylessAvroConverter.toConnectData(RegistrylessAvroConverter.java:126)`

I have no ideas as to why this error occurs? However I can say that Divolte produces records to Kafka without a schema. Does this cause the problem?

**Comment by OneCricketeer** [comment]
Are you sure there's no schema id with those records? Last I checked, Divollte can integrate with the Confluent registry, and may do so, by default, for its Avro events
